CREATE DATABASE IF NOT EXISTS tarlam_takipte
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_turkish_ci;

USE tarlam_takipte;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(80) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_turkish_ci;

CREATE TABLE IF NOT EXISTS fields (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  tarla_adi VARCHAR(120) NOT NULL,
  lokasyon VARCHAR(180) DEFAULT NULL,
  alan DECIMAL(10,2) NOT NULL DEFAULT 0,
  urun VARCHAR(120) DEFAULT NULL,
  gubre DECIMAL(10,2) NOT NULL DEFAULT 0,
  gubre_fiyat DECIMAL(10,2) NOT NULL DEFAULT 0,
  mazot DECIMAL(10,2) NOT NULL DEFAULT 0,
  mazot_fiyat DECIMAL(10,2) NOT NULL DEFAULT 0,
  verim DECIMAL(10,2) NOT NULL DEFAULT 0,
  satis DECIMAL(10,2) NOT NULL DEFAULT 0,
  tur ENUM('Hızlı Kayıt', 'Normal Kayıt', 'Detaylı Kayıt') NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_fields_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_turkish_ci;

CREATE INDEX idx_fields_user_id ON fields(user_id);
